Lab9Data<-read.csv(file.choose(),header=T)
summary(Lab9Data)
Lab9Data$cylinders<-(Lab9Data$cylinders-min(Lab9Data$cylinders))/(max(Lab9Data$cylinders)-min(Lab9Data$cylinders))
Lab9Data$cubicinches<-(Lab9Data$cubicinches-min(Lab9Data$cubicinches))/(max(Lab9Data$cubicinches)-min(Lab9Data$cubicinches))
Lab9Data$weightlbs<-(Lab9Data$weightlbs-min(Lab9Data$weightlbs))/(max(Lab9Data$weightlbs)-min(Lab9Data$weightlbs))
summary(Lab9Data)
clusters <- hclust (dist (Lab9Data[, 2:3,5]))
plot(clusters)
clusterCut <- cutree(clusters, 3)
Lab9Data$label <-clusterCut
install.packages("ggplot2")
library(ggplot2)
qplot(x=label,y=mpg, data=Lab9Data)
meanmpg<-aggregate(Lab9Data$mpg,list(Lab9Data$label),mean) 
colnames(meanmpg)<-c("cluster", "averagempg")
meanmpg
barplot(meanmpg$averagempg,main="AverageMPG",names.arg=meanmpg$cluster,xlab="cluster")
summary(aov (mpg ~ factor (label), data=Lab9Data))
write.csv(Lab9Data, file= "Lab9Data.csv")
