Lab11Data<-read.csv(file.choose(),header=FALSE, sep="\t", quote="", stringsAsFactors=FALSE)
colnames (Lab11Data) <- c("type", "text")
str(Lab11Data)
install.packages("tm")
library(tm)
Lab11Doc<-Corpus(VectorSource(Lab11Data$text))
Lab11Doc1<-tm_map(Lab11Doc, removePunctuation)
Lab11Doc1<-tm_map (Lab11Doc1, tolower)
Lab11Doc1<-tm_map(Lab11Doc1, removeWords, stopwords (kind="en"))
Lab11Doc1<-tm_map (Lab11Doc1, stripWhitespace)
Lab11Doc1<-tm_map (Lab11Doc1, removeNumbers)
Lab11Doc2<-TermDocumentMatrix(Lab11Doc1)
findFreqTerms (Lab11Doc2, lowfreq = 100)
findAssocs (Lab11Doc2, terms = "call", corlimit = 0.1)
Lab11Matrix<-as.matrix(Lab11Doc2)
Lab11_freqs = sort(rowSums(Lab11Matrix), decreasing=TRUE)
Lab11DF = data.frame(word=names(Lab11_freqs), freq=Lab11_freqs)
head(Lab11DF, 20)
library(ggplot2)
Lab11DF_top<-Lab11DF[1:20,]
ggplot(Lab11DF_top, aes(x = word, y = freq))+geom_bar (stat = "identity") + coord_flip() + labs (title = "Most Frequent words")
install.packages("wordcloud")
library(wordcloud)
set.seed(123)
wordcloud(word=Lab11DF$word, freq=Lab11DF$freq, max.words=200, random.order=FALSE, colors=brewer.pal(8, "Dark2"))
