zipcode<-read.delim(file.choose(),header=F)
head(zipcode)
names(zipcode)<-c("country_code","postal_code","place","state","st","county",
                  "countycode","community","communitycode","latitude","longitude","accuracy")
names(zipcode)
str(zipcode)
zipcode$postal_code<-as.character(zipcode$postal_code)
str(zipcode)
install.packages("dplyr")
library(dplyr)
Lab3_4<-inner_join(Lab3_3,zipcode,by=c("RegionID"="postal_code"))
head(Lab3_4)
str(Lab3_4)
write.csv(Lab3_4, file - "Lab3_4.csv" )