# Generated by Django 5.0.8 on 2024-10-09 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
