# Generated by Django 5.0.8 on 2024-10-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeimage',
            old_name='description',
            new_name='ingredients',
        ),
        migrations.AddField(
            model_name='recipeimage',
            name='instructions',
            field=models.TextField(blank=True),
        ),
    ]
