# Generated by Django 5.0.8 on 2024-10-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_images', '0002_rename_description_recipeimage_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeimage',
            name='link',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
